### ISSUE TITLE
have news to make the site more lively

### ISSUE THREAD

**Issue by aoloe** [libregraphicsmeeting/htdocs-2018#1]
in the past the site has mostly been very static.

we should make it easy:

- to post news before the lgm (what happens in the projects attending the lgm? how the lgm is progressing?)
- to post news during the lgm (what happened today? what will happen tomorrow?)

**Comment by davelab6** [comment]
I guess that anyone who wants to propose a WordPress post who does not have access to http://libregraphicsmeeting.org/2018/wp/wp-admin can do so by posting an issue here with their post draft inline, or a link to where it can be found :)
