### ISSUE TITLE
/2018/contact links to wrong repo issue tracker

### ISSUE THREAD

**Issue by davelab6** [libregraphicsmeeting/htdocs-2018#5]
http://libregraphicsmeeting.org/2018/contact/ says

> For issues regarding the website, you are welcome to [report them in our bugtracker.](https://github.com/libregraphicsmeeting/htdocs-2015/issues)

This link target is 

https://github.com/libregraphicsmeeting/htdocs-2015/issues

It should be

https://github.com/libregraphicsmeeting/htdocs-2018/issues

**Comment by aoloe** [comment]
fixed
