### ISSUE TITLE
Pinned tweet is outdated

### ISSUE THREAD

**Issue by davelab6** [libregraphicsmeeting/htdocs-2018#6]
https://twitter.com/LGMeeting/status/831926415373324292 is the current pinned tweet for the 2017 event, a tweet about 2018 should be made and pinned

**Comment by aoloe** [comment]
@xuv can you please have a look at this?

**Comment by xuv** [comment]
@aoloe @davelab6 Thx for these headsup. Indeed the Twitter account needs some love. Header image and description could also be updated to reflect the current status of LGM. I will handle this later this week.

**Comment by xuv** [comment]
Done: https://twitter.com/LGMeeting/status/940414888673005570 ;)
(Apparently I can't close this issue, so if someone can close it for me, thx.)

**Comment by davelab6** [comment]
Thank you Julien!
